
steps:
    - name: gcr.io/cloud-builders/docker
      args: ['run', '-d', '--network=cloudbuild', '--env=POSTGRES_HOST_AUTH_METHOD=trust', '--name=postgresql', 'postgres:14.1',]

    - id: 'database-ready'
      name: jwilder/dockerize:0.6.1
      args: ['dockerize', '-timeout=60s', '-wait=tcp://postgresql:5432']

    # GitHub Authentication
    - id: 'github-auth'
      name: 'bash:latest'
      entrypoint: 'bash'
      args:
        - '-c'
        - 'echo "{\"github-oauth\":{\"github.com\":\"$$GITHUB_ACCESS_TOKEN\"}}" > auth.json'
        - 'echo \"//npm.pkg.github.com/:$$GITHUB_ACCESS_TOKEN\" > .npmrc'
      secretEnv:
        - "GITHUB_ACCESS_TOKEN"

    # Composer install
    - id: 'composer-install'
      name: ubitransport/php-tools:ci-php8.1
      waitFor: ['github-auth']
      entrypoint: sh
      args:
        - '-c'
        - |-
          composer install

    # fixer
    - id: 'fixer'
      name: ubitransport/php-tools:ci-php8.1
      waitFor: ['composer-install']
      entrypoint: sh
      args:
        - '-c'
        - |-
          php-cs-fixer fix --config=/root/.composer/vendor/ubitransport/coding-standards/config/.php_cs_microservice.dist --verbose --dry-run --diff

    # phpstan
    - id: 'phpstan'
      name: ubitransport/php-tools:ci-php8.1
      waitFor: ['composer-install']
      entrypoint: sh
      args:
        - '-c'
        - |-
          ls -l
          php bin/phpunit --filter=testGreatingsFromPlanetEarth
          php vendor/bin/phpstan

    # tests
    - id: 'tests'
      name: ubitransport/php-tools:ci-php8.1
      waitFor: ['composer-install']
      entrypoint: sh
      args:
        - '-c'
        - |
          sudo chmod u+x ./.ci/tests \
          && ./.ci/tests

options:
    machineType: 'E2_HIGHCPU_8'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github-access-token/versions/latest
      env: 'GITHUB_ACCESS_TOKEN'
